/** Display names for compiled GTM template functions (function name without the leading `__`). */
export const TAG_TYPES: Record<string, { name: string; short?: string; group: string; icon: string }> = {
  gaawe: { name: "Google Analytics: GA4 Event", short: "GA4 Event", group: "Google Analytics", icon: "ga" },
  ga4_event: { name: "Google Analytics: GA4 Event", short: "GA4 Event", group: "Google Analytics", icon: "ga" },
  gaawc: { name: "Google Analytics: GA4 Configuration", short: "GA4 Configuration", group: "Google Analytics", icon: "ga" },
  ua: { name: "Google Analytics: Universal Analytics", short: "Universal Analytics", group: "Google Analytics", icon: "ga" },
  googtag: { name: "Google Tag", group: "Google", icon: "google" },
  gclidw: { name: "Conversion Linker", group: "Google", icon: "google" },
  awct: { name: "Google Ads Conversion Tracking", short: "Google Ads Conversion", group: "Google Ads", icon: "ads" },
  awcc: { name: "Google Ads Calls from Website Conversion", group: "Google Ads", icon: "ads" },
  sp: { name: "Google Ads Remarketing", group: "Google Ads", icon: "ads" },
  awud: { name: "Google Ads User-Provided Data Event", group: "Google Ads", icon: "ads" },
  flc: { name: "Floodlight Counter", group: "Floodlight", icon: "ads" },
  fls: { name: "Floodlight Sales", group: "Floodlight", icon: "ads" },
  html: { name: "Custom HTML", group: "Custom", icon: "code" },
  img: { name: "Custom Image", group: "Custom", icon: "image" },
  baut: { name: "Microsoft Advertising Universal Event Tracking", group: "Microsoft Advertising", icon: "code" },
  bzi: { name: "LinkedIn Insight", group: "LinkedIn", icon: "code" },
  hjtc: { name: "Hotjar Tracking Code", group: "Hotjar", icon: "code" },
  pntr: { name: "Pinterest Tag", group: "Pinterest", icon: "code" },
  crto: { name: "Criteo OneTag", group: "Criteo", icon: "code" },
  qpx: { name: "Quora Pixel", group: "Quora", icon: "code" },
  twitter_website_tag: { name: "Twitter Universal Website Tag", group: "X / Twitter", icon: "code" },
  asp: { name: "AdRoll Smart Pixel", group: "AdRoll", icon: "code" },
  opt: { name: "Google Optimize", group: "Google", icon: "google" },
  gcs: { name: "Google Consent Signals", group: "Google", icon: "google" },
  zone: { name: "Zone", group: "Google", icon: "google" },
};

/** Auto-event listener templates that GTM compiles in for triggers; not user-created tags. */
export const LISTENER_TAGS = new Set(["lcl", "cl", "fsl", "hl", "sdl", "evl", "ytl", "tl", "jel", "ehl", "fil", "fcl", "fsl", "pvl"]);

export const LISTENER_TRIGGER: Record<string, string> = {
  lcl: "Just Links", cl: "All Elements", fsl: "Form Submission", hl: "History Change", sdl: "Scroll Depth",
  evl: "Element Visibility", ytl: "YouTube Video", tl: "Timer", jel: "JavaScript Error",
};

export interface TriggerTypeInfo { name: string; icon: string; exportType: string; all: string }

export const TRIGGER_BY_EVENT: Record<string, TriggerTypeInfo> = {
  "gtm.js": { name: "Page View", icon: "visibility", exportType: "PAGEVIEW", all: "All Page Views" },
  "gtm.dom": { name: "DOM Ready", icon: "web_asset", exportType: "DOM_READY", all: "DOM Ready" },
  "gtm.load": { name: "Window Loaded", icon: "web_asset", exportType: "WINDOW_LOADED", all: "Window Loaded" },
  "gtm.init": { name: "Initialization", icon: "power_settings_new", exportType: "INIT", all: "Initialization - All Pages" },
  "gtm.init_consent": { name: "Consent Initialization", icon: "shield", exportType: "CONSENT_INIT", all: "Consent Initialization - All Pages" },
  "gtm.linkClick": { name: "Just Links", icon: "link", exportType: "LINK_CLICK", all: "All Links" },
  "gtm.click": { name: "All Elements", icon: "mouse", exportType: "CLICK", all: "All Clicks" },
  "gtm.formSubmit": { name: "Form Submission", icon: "assignment", exportType: "FORM_SUBMISSION", all: "All Forms" },
  "gtm.historyChange": { name: "History Change", icon: "history", exportType: "HISTORY_CHANGE", all: "All History Changes" },
  "gtm.historyChange-v2": { name: "History Change", icon: "history", exportType: "HISTORY_CHANGE", all: "All History Changes" },
  "gtm.scrollDepth": { name: "Scroll Depth", icon: "control_camera", exportType: "SCROLL_DEPTH", all: "Scroll Depth" },
  "gtm.elementVisibility": { name: "Element Visibility", icon: "visibility", exportType: "ELEMENT_VISIBILITY", all: "Element Visibility" },
  "gtm.video": { name: "YouTube Video", icon: "smart_display", exportType: "YOU_TUBE_VIDEO", all: "YouTube Video" },
  "gtm.timer": { name: "Timer", icon: "timer", exportType: "TIMER", all: "Timer" },
  "gtm.pageError": { name: "JavaScript Error", icon: "error", exportType: "JS_ERROR", all: "All JavaScript Errors" },
};

export const CUSTOM_EVENT: TriggerTypeInfo = { name: "Custom Event", icon: "code", exportType: "CUSTOM_EVENT", all: "All Custom Events" };

export const VARIABLE_TYPES: Record<string, { name: string; icon: string }> = {
  v: { name: "Data Layer Variable", icon: "database" },
  u: { name: "URL", icon: "language" },
  jsm: { name: "Custom JavaScript", icon: "code" },
  j: { name: "JavaScript Variable", icon: "javascript" },
  k: { name: "1st-Party Cookie", icon: "cookie" },
  c: { name: "Constant", icon: "tag" },
  smm: { name: "Lookup Table", icon: "table" },
  remm: { name: "RegEx Table", icon: "table" },
  d: { name: "DOM Element", icon: "html" },
  aev: { name: "Auto-Event Variable", icon: "ads_click" },
  f: { name: "HTTP Referrer", icon: "language" },
  e: { name: "Custom Event", icon: "bolt" },
  r: { name: "Random Number", icon: "casino" },
  ctv: { name: "Container Version Number", icon: "tag" },
  cid: { name: "Container ID", icon: "tag" },
  dbg: { name: "Debug Mode", icon: "bug_report" },
  gas: { name: "Google Analytics Settings", icon: "settings" },
  gtes: { name: "Google Tag: Event Settings", icon: "settings" },
  gtcs: { name: "Google Tag: Configuration Settings", icon: "settings" },
  awec: { name: "User-Provided Data", icon: "contacts" },
  vis: { name: "Element Visibility", icon: "visibility" },
  uv: { name: "Undefined Value", icon: "block" },
  t: { name: "Environment Name", icon: "dns" },
  hid: { name: "HTML ID", icon: "settings" },
  analytics_storage: { name: "Analytics Storage", icon: "database" },
  gtm_ctid: { name: "Container ID", icon: "tag" },
  sdl: { name: "Scroll Depth", icon: "control_camera" },
};

/** Built-in GTM variables as they appear once compiled (Data Layer Variable v1 keys). */
export const BUILT_IN_DLV: Record<string, { name: string; exportType: string }> = {
  "gtm.element": { name: "Click Element", exportType: "CLICK_ELEMENT" },
  "gtm.elementClasses": { name: "Click Classes", exportType: "CLICK_CLASSES" },
  "gtm.elementId": { name: "Click ID", exportType: "CLICK_ID" },
  "gtm.elementTarget": { name: "Click Target", exportType: "CLICK_TARGET" },
  "gtm.elementUrl": { name: "Click URL", exportType: "CLICK_URL" },
  "gtm.newUrlFragment": { name: "New History Fragment", exportType: "NEW_HISTORY_FRAGMENT" },
  "gtm.oldUrlFragment": { name: "Old History Fragment", exportType: "OLD_HISTORY_FRAGMENT" },
  "gtm.newHistoryState": { name: "New History State", exportType: "NEW_HISTORY_STATE" },
  "gtm.oldHistoryState": { name: "Old History State", exportType: "OLD_HISTORY_STATE" },
  "gtm.historyChangeSource": { name: "History Source", exportType: "HISTORY_SOURCE" },
  "gtm.videoProvider": { name: "Video Provider", exportType: "VIDEO_PROVIDER" },
  "gtm.videoUrl": { name: "Video URL", exportType: "VIDEO_URL" },
  "gtm.videoTitle": { name: "Video Title", exportType: "VIDEO_TITLE" },
  "gtm.videoDuration": { name: "Video Duration", exportType: "VIDEO_DURATION" },
  "gtm.videoPercent": { name: "Video Percent", exportType: "VIDEO_PERCENT" },
  "gtm.videoVisible": { name: "Video Visible", exportType: "VIDEO_VISIBLE" },
  "gtm.videoStatus": { name: "Video Status", exportType: "VIDEO_STATUS" },
  "gtm.videoCurrentTime": { name: "Video Current Time", exportType: "VIDEO_CURRENT_TIME" },
  "gtm.scrollThreshold": { name: "Scroll Depth Threshold", exportType: "SCROLL_DEPTH_THRESHOLD" },
  "gtm.scrollUnits": { name: "Scroll Depth Units", exportType: "SCROLL_DEPTH_UNITS" },
  "gtm.scrollDirection": { name: "Scroll Direction", exportType: "SCROLL_DEPTH_DIRECTION" },
  "gtm.visibleRatio": { name: "Percent Visible", exportType: "PERCENT_VISIBLE" },
  "gtm.visibleTime": { name: "On-Screen Duration", exportType: "ON_SCREEN_DURATION" },
  "gtm.errorMessage": { name: "Error Message", exportType: "ERROR_MESSAGE" },
  "gtm.errorUrl": { name: "Error URL", exportType: "ERROR_URL" },
  "gtm.errorLineNumber": { name: "Error Line", exportType: "ERROR_LINE" },
  "gtm.triggers": { name: "Trigger IDs (internal)", exportType: "" },
};

/** Vendors recognized inside Custom HTML / image tags by the domains or globals they reference. */
export const VENDORS: Array<{ name: string; pattern: RegExp; idPattern?: RegExp }> = [
  { name: "Meta Pixel", pattern: /connect\.facebook\.net|facebook\.com\/tr|\bfbq\(/i, idPattern: /fbq\(\s*["']init["']\s*,\s*["'](\d{6,})["']|facebook\.com\/tr\?id=(\d{6,})/gi },
  { name: "Microsoft Clarity", pattern: /clarity\.ms|["']clarity["']/i },
  { name: "Hotjar", pattern: /static\.hotjar\.com|hotjar/i, idPattern: /hjid\s*:\s*(\d+)/gi },
  { name: "LinkedIn Insight", pattern: /snap\.licdn\.com|_linkedin_partner_id|px\.ads\.linkedin/i, idPattern: /_linkedin_partner_id\s*=\s*["']?(\d+)/gi },
  { name: "TikTok Pixel", pattern: /analytics\.tiktok\.com|\bttq\./i, idPattern: /ttq\.load\(\s*["']([A-Z0-9]+)["']/gi },
  { name: "Microsoft Advertising", pattern: /bat\.bing\.com|\buetq\b/i, idPattern: /\bti\s*:\s*["']?(\d+)/gi },
  { name: "X / Twitter", pattern: /static\.ads-twitter\.com|\btwq\(/i, idPattern: /twq\(\s*["'](?:init|config)["']\s*,\s*["']([a-z0-9]+)["']/gi },
  { name: "Pinterest", pattern: /pintrk|s\.pinimg\.com\/ct/i, idPattern: /pintrk\(\s*["']load["']\s*,\s*["'](\d+)["']/gi },
  { name: "Snap Pixel", pattern: /sc-static\.net|\bsnaptr\(/i, idPattern: /snaptr\(\s*["']init["']\s*,\s*["']([a-f0-9-]+)["']/gi },
  { name: "Reddit Pixel", pattern: /redditstatic\.com|\brdt\(/i, idPattern: /rdt\(\s*["']init["']\s*,\s*["']([a-z0-9_]+)["']/gi },
  { name: "HubSpot", pattern: /hs-scripts\.com|js\.hs-analytics|hsforms/i, idPattern: /hs-scripts\.com\/(\d+)/gi },
  { name: "Intercom", pattern: /widget\.intercom\.io|intercomSettings/i },
  { name: "Criteo", pattern: /static\.criteo\.net|criteo_q/i },
  { name: "Taboola", pattern: /cdn\.taboola\.com|_tfa/i },
  { name: "Outbrain", pattern: /amplify\.outbrain\.com|obApi/i },
  { name: "Yandex Metrica", pattern: /mc\.yandex\.ru|\bym\(/i },
  { name: "Matomo", pattern: /matomo|piwik/i },
  { name: "Segment", pattern: /cdn\.segment\.com|analytics\.load\(/i },
  { name: "Mixpanel", pattern: /cdn\.mxpnl\.com|mixpanel\./i },
  { name: "Amplitude", pattern: /cdn\.amplitude\.com|amplitude\.getInstance/i },
  { name: "Heap", pattern: /cdn\.heapanalytics\.com|heap\.load/i },
  { name: "Klaviyo", pattern: /static\.klaviyo\.com|_learnq/i },
  { name: "Quora Pixel", pattern: /a\.quora\.com|\bqp\(/i },
  { name: "Microsoft Ads UET", pattern: /bat\.bing\.net/i },
  { name: "Google Ads", pattern: /googleadservices\.com|gtag\(\s*["']config["']\s*,\s*["']AW-/i, idPattern: /\b(AW-\d{6,})\b/g },
  { name: "Google Analytics", pattern: /google-analytics\.com|gtag\(\s*["']config["']\s*,\s*["']G-/i, idPattern: /\b(G-[A-Z0-9]{6,})\b/g },
  { name: "Cookie consent", pattern: /cookiebot|onetrust|cookieyes|didomi|usercentrics|iubenda|termly/i },
];

/** Friendly labels for common compiled `vtp_` parameter keys. */
export const PARAM_LABELS: Record<string, string> = {
  eventName: "Event Name",
  measurementIdOverride: "Measurement ID",
  measurementId: "Measurement ID",
  tagId: "Tag ID",
  eventSettingsTable: "Event Parameters",
  eventParameters: "Event Parameters",
  userProperties: "User Properties",
  configSettingsTable: "Configuration settings",
  sendEcommerceData: "Send Ecommerce data",
  enableUserProperties: "Enable user properties",
  enableEuid: "Enable euid",
  enhancedUserId: "Enhanced user id",
  migratedToV2: "Migrated to v2",
  demoV2: "Demo v2",
  conversionId: "Conversion ID",
  conversionLabel: "Conversion Label",
  conversionValue: "Conversion Value",
  currencyCode: "Currency Code",
  orderId: "Transaction ID",
  html: "HTML",
  supportDocumentWrite: "Support document.write",
  enableIframeMode: "Iframe mode",
  linkerDomains: "Auto-link domains",
  enableCrossDomain: "Enable linking on all page URLs",
  acceptIncoming: "Accept incoming linker parameters",
  urlPosition: "URL position",
  formDecoration: "Decorate forms",
  trackType: "Track Type",
  trackingId: "Tracking ID",
  gaSettings: "Google Analytics Settings",
  eventCategory: "Category",
  eventAction: "Action",
  eventLabel: "Label",
  eventValue: "Value",
  nonInteraction: "Non-Interaction Hit",
  phoneConversionNumber: "Phone number",
  enableConversionLinker: "Enable Conversion Linker",
  enableEnhancedConversion: "Include user-provided data from your website",
  cssProvidedEnhancedConversionValue: "User-provided data",
  enableProductReporting: "Provide product-level sales data",
  enableNewCustomerReporting: "New customer reporting",
  enableShippingData: "Shipping data",
  conversionCookiePrefix: "Conversion cookie prefix",
  rdp: "Restricted data processing",
  url: "Page URL",
  name: "Data Layer Variable Name",
  dataLayerVersion: "Data Layer Version",
  component: "Component Type",
  javascript: "Custom JavaScript",
  value: "Value",
  varType: "Variable Type",
  mode: "Mode",
  setDefaultValue: "Set Default Value",
  defaultValue: "Default Value",
  input: "Input Variable",
  map: "Lookup Table",
  cookieDomain: "Cookie Domain",
  dataField: "Data field",
};

export function humanizeKey(key: string): string {
  if (PARAM_LABELS[key]) return PARAM_LABELS[key];
  const spaced = key.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/_/g, " ").trim();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1).toLowerCase();
}

export function tagTypeInfo(fn: string) {
  if (TAG_TYPES[fn]) return TAG_TYPES[fn];
  if (fn.startsWith("cvt_")) return { name: `Custom Template (${fn})`, group: "Custom templates", icon: "extension" };
  return { name: humanizeKey(fn), group: "Other", icon: "sell" };
}
